Upadated doc files to integrate TLS
cetic/fadi pull request #148
Opened 2022-02-02 09:20 UTC by zakaria2905

- Updated USERGUIDE.md with .example.cetic.be domain names and single user nifi credentials
- Change SSL to TLS in README.md
- Updated REVERSEPROXY.md with .example.cetic.be domain names and adding the new ingressroute format
- Updated SECURITY.md to explain how to enable TLS using Cert-manager and Let's Encrypt
- Updated USERMANAGEMENT.md for new versions of Nifi (1.14.0) and Jupyterhub

2022-02-09 15:58 UTC, banzo requested changes

2022-02-09 15:58 UTC, banzo commented on doc/REVERSEPROXY.md
add link to official reference for configuring ingressroutes

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
> +We will use it to get certificates from e known certificate authority.
typo "e"?

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
> +else:
Need more context, for example with a link to install.md relevant step where this command takes place.

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
> +Let's suppose that you have created TLS for Grafana, if you type in your browser "http://grafana.flaracc.cetic.be", your will get an error.
* Should use a generic domain name, for example grafana.flaracc.cetic.be

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
> +You have to type "https://grafana.flaracc.cetic.be" to access Grafana in the secure mode.
* [x] can we do a [redirect](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/tasks/ssl_redirect/)?
* [x] use generic domain name

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
> +Finaly, upgrade your FADI deployment.
add the command for this

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
> +grafana.flaracc.cetic.be   True    grafana.flaracc.cetic.be   83m
change domain name

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
> +grafana.flaracc.cetic.be                      kubernetes.io/tls                     2      83m
change domain name

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
> +  email: <your e-mail address>
What is this email address used for? should it correspond to the Letsencrypt account?

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
> +It will be used to provide certificates to FADIS's services.
FADI's

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
> +Let's Encrypt is a non-profit certificate authority run by Internet Security Research Group (ISRG) that provides X.509 certificates for Transport Layer Security (TLS) encryption at no charge([wikiped
add a link to the official Letsencrypt website and ISRG when mentioned the first time.

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
> +Before upgrading your FADI deployment, you must choose the services on which you want to enable TLS. To do this, under each application section of the values.yaml file, navigate to the ingressTraefik
would it make sense to make this a subsection?

2022-02-09 15:58 UTC, banzo commented on doc/SECURITY.md
The page structure does not feel clear to me, I would suggest to add a brief summary of the process here, and then align the sections on it.

2022-02-09 15:58 UTC, banzo commented on doc/REVERSEPROXY.md
>  You should now be able to access Grafana through the domain name you have chosen: `http(s)://grafana.fadi.cetic.be`
this should be a link

2022-02-09 21:35 UTC, zakaria2905 commented on doc/SECURITY.md
> +You have to type "https://grafana.flaracc.cetic.be" to access Grafana in the secure mode.
not yet, but that will be the next step

2022-02-09 21:41 UTC, zakaria2905 commented on doc/SECURITY.md
> +  email: <your e-mail address>
there is no Letsencrypt account. The email is used to send, if needed, alerts about certificates

2022-02-09 21:50 UTC, zakaria2905 commented on doc/SECURITY.md
> +Before upgrading your FADI deployment, you must choose the services on which you want to enable TLS. To do this, under each application section of the values.yaml file, navigate to the ingressTraefik
I think it's possible that someone wants to deploy FADI's services without TLS or use their own TLS service no?

2022-02-24 09:59 UTC, banzo commented
* [ ] cleanup helm folder
* [ ] adapt installations instructions so we do not need to clone the fadi repo and just need to get the deploy.sh
* [ ] maybe we can get rid of the deploy.sh altogether

2022-05-27 13:40 UTC, banzo approved these changes

2022-05-27 13:40 UTC, banzo commented on doc/SECURITY.md
> +  email: <your e-mail address>
please add that explanation as a comment in the file

2022-05-27 13:41 UTC, merged